ch_cookie_consent: 
    categories: ['analytics', 'tracking', 'social_media', 'marketing']
    theme: 'light'
    use_logger: true
    position: 'top'
    simplified: false
    http_only: true
    form_action: accepted_cookie
    csrf_protection: true
